name: build

on:
  push:
  pull_request:
    branches: [ lab6 ]
    paths:
    - '/.cs'
    - '/.csproj'

env:
  DOTNET_VERSION: '8.0' # The .NET SDK version to use

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install dependencies
      run: dotnet restore lab6/lab6.sln
      
    - name: Build
      run: dotnet build lab6/lab6.sln --configuration Release --no-restore
