name: build

on:
  push:
  pull_request:
    branches: [ lab5 ]
    paths:
    - '/.cs'
    - '/.csproj'

env:
  DOTNET_VERSION: '8.0' # The .NET SDK version to use

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore C:/Users/User/Desktop/temp/CustomMVC.csproj

    - name: Install dependencies for test project
      run: dotnet restore C:/Users/User/Desktop/Tests/Tests.csproj

    - name: Build
      run: dotnet C:/Users/User/Desktop/temp/CustomMVC.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test C:/Users/User/Desktop/Tests/Tests.csproj --no-restore --verbosity normal
